email_mapping = {
    "CA": "canada@loshara.com",
    "NZ": "newzealand@loshara.com",
    "AT": "austria@loshara.com",
    "AU": "australia@loshara.com",
    "CH": "switzerland@loshara.com",
    "IE": "ireland@loshara.com",
    "NO": "norway@loshara.com",
    "CY": "cyprus@loshara.com",
    "DE": "germany@loshara.com",
    "DK": "denmark@loshara.com",
    "ZA": "safrica@loshara.com",
    "PH": "philippines@loshara.com",
    "JP": "japan@loshara.com",
    "IN": "india@loshara.com",
    "IT": "italy@loshara.com",
    "LU": "luxembourg@loshara.com",
    "BR": "brazil@loshara.com",
    "SI": "slovenia@loshara.com",
    "IS": "iceland@loshara.com",
    "KR": "hiowffioQHWEFIofhn@kbc.pp.ua",  # South Korea
    "MX": "babibu@kingbilly.xyz",  # Mexico
    "AR": "argentina@kingbilly.xyz",
    "CL": "chilie@kingbilly.xyz",
    "BG": "Bulgaria@loshara.com"
}

country_translations = {
    "CA": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "NZ": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "AU": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "IE": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "NO": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "CY": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "DK": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "ZA": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "PH": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "JP": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "IN": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "IT": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "LU": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "BR": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "SI": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "IS": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "KR": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "MX": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "AR": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "CL": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "KH": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "BD": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "TW": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "LA": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "AT": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "CH": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "BG": {"locale": "EN", "translations": {"login": "Log in", "email_placeholder": "Enter your email", "password_placeholder": "Enter your password", "deposit_button": "Deposit", "wallet_link": "Wallet", "withdrawal_link": "Withdrawal", "decline_button": "Decline", "my_account": "My Account"}},
    "DE": {"locale": "DE", "translations": {"login": "Anmelden", "email_placeholder": "E-Mail-Adresse eingeben", "password_placeholder": "Passwort eingeben", "deposit_button": "Einzahlen", "wallet_link": "Geldbörse", "withdrawal_link": "Auszahlung", "decline_button": "Ablehnen", "my_account": "Mein Konto"}},
}